name: po8_images
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/facebook.jpeg
    - images/instagram.png
    - images/youtube.jpeg
    - images/twitter.jpeg
    - images/whatsApp.jpeg
    - images/linkedin.png
    - images/GooglePlus.jpeg
    - images/snapchat.jpeg
    - images/Skype.jpeg
    - images/Spotify.jpeg

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Black.ttf
        - asset: fonts/PlayfairDisplay-BlackItalic.ttf
          style: italic
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: fonts/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: fonts/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: fonts/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: fonts/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: JosefinSans
      fonts:
        - asset: fonts/Josefin_Sans/static/JosefinSans-Regular.ttf
